"""add iaas_user

Revision ID: 234a663c437c
Revises: f5dc00405782
Create Date: 2024-01-26 05:21:31.614461

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '234a663c437c'
down_revision: Union[str, None] = 'f5dc00405782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iaas_requests', sa.Column('iaas_user', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iaas_requests', 'iaas_user')
    # ### end Alembic commands ###
