"""add job_id

Revision ID: 38e997d41924
Revises: 234a663c437c
Create Date: 2024-01-29 04:35:53.269951

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38e997d41924'
down_revision: Union[str, None] = '234a663c437c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iaas_requests', sa.Column('job_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iaas_requests', 'job_id')
    # ### end Alembic commands ###
