"""add table comment

Revision ID: 67af78d4c91d
Revises: bbe2726d33bd
Create Date: 2024-02-22 02:27:51.824243

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67af78d4c91d'
down_revision: Union[str, None] = 'bbe2726d33bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
