"""re-init

Revision ID: da63cd8df487
Revises: 
Create Date: 2025-04-01 04:22:17.744759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da63cd8df487'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='User activities'
    )
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Global configurations'
    )
    op.create_table('iaas_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('request_deadline', sa.DateTime(), nullable=False),
    sa.Column('request_user', sa.String(length=32), nullable=False),
    sa.Column('iaas_user', sa.String(length=32), nullable=True),
    sa.Column('request_status', sa.String(length=32), nullable=False),
    sa.Column('request_category', sa.String(length=255), nullable=False),
    sa.Column('request_operation', sa.String(length=255), nullable=False),
    sa.Column('request_text', sa.String(length=255), nullable=False),
    sa.Column('job_options', sa.JSON(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='IaaS requests'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iaas_requests')
    op.drop_table('configurations')
    op.drop_table('activities')
    # ### end Alembic commands ###
