"""init

Revision ID: f5dc00405782
Revises: 
Create Date: 2024-01-25 13:24:32.046494

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5dc00405782'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iaas_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('request_deadline', sa.DateTime(), nullable=False),
    sa.Column('request_user', sa.String(length=32), nullable=False),
    sa.Column('request_status', sa.String(length=32), nullable=False),
    sa.Column('request_category', sa.String(length=255), nullable=False),
    sa.Column('request_operation', sa.String(length=255), nullable=False),
    sa.Column('request_text', sa.String(length=255), nullable=False),
    sa.Column('job_options', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iaas_requests')
    # ### end Alembic commands ###
